<!-- 
    Title: order.html
    Author: Sarim Khan
    Purpose: To provide an order page for the user. 
    Course: CSCI 450-01 
 --> 
 <html> 
        <head>
            <title>Five Star Electric</title> 
            <link rel='stylesheet' type='text/css' href='style.css'>
            <meta name='viewport' content='width=device-width, initial-scale=1.0'>
            <script language='javascript' src='ordersubmit.js'></script> 
        </head> <!-- close head -->
    <body>
    <div id='header'>
        <img src = 'logo.jpg'> </img>
    </div>
                <!-- List title with bold and center edits --> 
    <p>
        <ul id='menu'>
            <li><a href='index.html'>Home</a></li> 
            <li><a href='products.html'>Services</a></li>
            <li><a href='reviews.html'>Reviews</a></li>
            <li><a href='contactUs.html'>Contact Us</a></li>
            <li class='active'><a href='order.html'>Place Order</a></li>
            <li><a href='cart.html'>Cart</a></li>
        </ul> <!-- list item hyperlinks to associated pages -->
    </p>
    <div class="content">